### ISSUE TITLE
Stop at Create New Item in Opensea

### ISSUE THREAD

**Issue by dseah** [lakshyabatman/Bulk-uploader-NFT#10]
Hi, my script stopped at creating new item in Opensea with the following error. What could be the possible causes?

`main.py:97: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(executable_path=CHROME_DRIVER_PATH, chrome_options=opt)
main.py:97: DeprecationWarning: use options instead of chrome_options
  driver = webdriver.Chrome(executable_path=CHROME_DRIVER_PATH, chrome_options=opt)
main.py:28: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  d.find_element_by_xpath('//button[text()="Import wallet"]').click()
main.py:31: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  d.find_element_by_xpath('//button[text()="No Thanks"]').click()
main.py:34: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  inputs = d.find_elements_by_xpath("//input")
main.py:41: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  d.find_element_by_css_selector(".first-time-flow__terms").click()
main.py:42: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  d.find_element_by_xpath('//button[text()="Import"]').click()
Traceback (most recent call last):
  File "main.py", line 101, in <module>
    signin_to_opensea(driver)
  File "main.py", line 55, in signin_to_opensea
    d.switch_to.window(d.window_handles[3])
IndexError: list index out of range`

**Comment by lakshyabatman** [comment]
The issue is related to  `File "main.py", line 55, in signin_to_opensea d.switch_to.window(d.window_handles[3])` when this error occurs, see how many tabs are opened on your driver page.
