### ISSUE TITLE
Won't login to OpenSea

### ISSUE THREAD

**Issue by aborriginal** [lakshyabatman/Bulk-uploader-NFT#6]
`nft@pc:~/Desktop/Bulk-uploader-NFT-main$ python3 main.py
/home/nft/Desktop/Bulk-uploader-NFT-main/main.py:97: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(executable_path=CHROME_DRIVER_PATH, chrome_options=opt)
/home/nft/Desktop/Bulk-uploader-NFT-main/main.py:97: DeprecationWarning: use options instead of chrome_options
  driver = webdriver.Chrome(executable_path=CHROME_DRIVER_PATH, chrome_options=opt)
/home/nft/Desktop/Bulk-uploader-NFT-main/main.py:28: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  d.find_element_by_xpath('//button[text()="Import wallet"]').click()
/home/nft/Desktop/Bulk-uploader-NFT-main/main.py:31: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  d.find_element_by_xpath('//button[text()="No Thanks"]').click()
/home/nft/Desktop/Bulk-uploader-NFT-main/main.py:34: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  inputs = d.find_elements_by_xpath("//input")
/home/nft/Desktop/Bulk-uploader-NFT-main/main.py:41: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  d.find_element_by_css_selector(".first-time-flow__terms").click()
/home/nft/Desktop/Bulk-uploader-NFT-main/main.py:42: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  d.find_element_by_xpath('//button[text()="Import"]').click()
Traceback (most recent call last):
  File "/home/nft/Desktop/Bulk-uploader-NFT-main/main.py", line 101, in <module>
    signin_to_opensea(driver)
  File "/home/nft/Desktop/Bulk-uploader-NFT-main/main.py", line 55, in signin_to_opensea
    d.switch_to.window(d.window_handles[3])
IndexError: list index out of range
`

**Comment by lakshyabatman** [comment]
The automation scripts sometimes throw random errors, I see `d.window_handles`'s length is lesser than 3. Probably in your case new window isn't opening up.
